/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.iffar.catra.forms;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

import br.edu.iffar.catra.comunica.KeycloakSession;
import br.edu.iffar.catra.control.PrincipalControl;
import br.edu.iffar.catra.control.SincronizadorControl;
import br.edu.iffar.catra.dao.APIImagemDAO;
import br.edu.iffar.catra.dao.APISincronizadoDAO;
import br.edu.iffar.catra.util.CallBack;
import br.edu.iffar.catra.util.CamCaptureThread;
import br.edu.iffar.catra.util.CamCreatorThread;
import br.edu.iffar.catra.util.Log;
import br.edu.iffar.fw.classBag.db.model.TipoRefeicao;
import br.edu.iffar.fw.classBag.db.model.api.APIAgendamento;
import br.edu.iffar.fw.classBag.db.model.api.APIImagen;
import br.edu.iffar.fw.classBag.db.model.api.APISaldo;

/**
 *
 * @author qwerty
 */
public class FormCatra extends javax.swing.JFrame implements CallBack<String> {


	private static FormCatra formCatra = new FormCatra(); 
	
	private static final long serialVersionUID = 1L;
    private APISincronizadoDAO apiSincronizadoDAO = new APISincronizadoDAO();
    private APIImagemDAO imagemCDAO = new APIImagemDAO();
    
    
    public static FormCatra getInstance() {
    	return formCatra;
    }
    
    public FormCatra() {
        initComponents();
    }

    public void initCam(CamCreatorThread creator) {

    	if(creator.getWebCam() == null) {
    		this.showMessageError("Web Cam não foi encontrada!");
//    		JOptionPane.showMessageDialog(null, "Web Cam não foi encontrada!");
	    	return;
    	}
    	
        CamCaptureThread capture = new CamCaptureThread(creator);
        capture.registerCamBack(this);
        capture.start();

        this.panelCam.setLayout(new FlowLayout());
        this.panelCam.add(creator.getPanel());
    }
    
	public void init() {
    	this.setLabelSincronizado(this.apiSincronizadoDAO.getUltimoSinc().getLabel());
        this.setVisibleBtnAcessos(false);
    }
    
    public void setLabelSincronizado(String texto) {
    	this.labelSincronizado.setText(texto);
    }
    
    
    /**
     * usado quando o usuario seleciona o tipo de refeicao no splat de inicialização
     * 
     * @param tiporefeicao 
     */
    public void setTipoRefeicao(TipoRefeicao tiporefeicao) {
    	 PrincipalControl.getPrincipalControl().setTipoRefeicao(tiporefeicao);
//    	 this.labelRefeicao.setText(tiporefeicao.getDescricao());
    	 this.txtTipoRefeicao.setText(tiporefeicao.getDescricao());
    	 
    	 this.txtTipoRefeicao.setDisabledTextColor(java.awt.Color.decode(tiporefeicao.getBackgroundColor()));
    	 setTitle("Catraca Virtual - "+tiporefeicao.getDescricao());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCatraca = new javax.swing.JPanel();
        textUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblRefeicao = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtTipoRefeicao = new javax.swing.JTextField();
        panelCam = new javax.swing.JPanel();
        panelInfoUser = new javax.swing.JPanel();
        labelImage = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        panelAgendado = new javax.swing.JPanel();
        txtPeriodoAgendado = new javax.swing.JTextField();
        txtRefeicaoAgendada = new javax.swing.JTextField();
        txtValorAgendamento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbldescTipoAgendamento = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        panelBtnAgendamento = new javax.swing.JPanel();
        btnCreditoCreditar = new javax.swing.JButton();
        btnCreditorCancelar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        scrollpMessages = new javax.swing.JScrollPane();
        panelMessages = new javax.swing.JPanel();
        pnlRodape = new javax.swing.JPanel();
        labelLogado = new javax.swing.JLabel();
        labelSincronizado = new javax.swing.JLabel();
        labelWebService = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelImgAcesso = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOpcoes = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();
        menuSincronizar = new javax.swing.JMenuItem();
        menuLogEvent = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Catraca Virtual");
        setBackground(new java.awt.Color(0, 102, 0));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                actionCloseWindow(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCatraca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textUserName.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        textUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUserNameActionPerformed(evt);
            }
        });
        textUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textUserNameKeyPressed(evt);
            }
        });
        panelCatraca.add(textUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 210, 30));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setText("Usuário:");
        panelCatraca.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        lblRefeicao.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblRefeicao.setText("Refeição:");
        panelCatraca.add(lblRefeicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        btnBuscar.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        btnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textUserNameKeyPressed(evt);
            }
        });
        panelCatraca.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 100, 30));

        txtTipoRefeicao.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtTipoRefeicao.setText("-");
        txtTipoRefeicao.setDisabledTextColor(new java.awt.Color(255, 0, 51));
        txtTipoRefeicao.setDoubleBuffered(true);
        txtTipoRefeicao.setEnabled(false);
        txtTipoRefeicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoRefeicaoActionPerformed(evt);
            }
        });
        panelCatraca.add(txtTipoRefeicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 210, 30));

        getContentPane().add(panelCatraca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 400, 80));

        panelCam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelCam.setMaximumSize(new java.awt.Dimension(480, 400));
        panelCam.setPreferredSize(new java.awt.Dimension(0, 0));
        panelCam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 330, 250));

        panelInfoUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInfoUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelInfoUser.setFocusable(false);
        panelInfoUser.setOpaque(false);
        panelInfoUser.setRequestFocusEnabled(false);
        panelInfoUser.setVerifyInputWhenFocusTarget(false);

        labelImage.setBackground(new java.awt.Color(0, 102, 51));
        labelImage.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelInfoUserLayout = new javax.swing.GroupLayout(panelInfoUser);
        panelInfoUser.setLayout(panelInfoUserLayout);
        panelInfoUserLayout.setHorizontalGroup(
            panelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelInfoUserLayout.setVerticalGroup(
            panelInfoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(panelInfoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 10, 330, 250));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 10, 630));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 390, 20));

        panelAgendado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPeriodoAgendado.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtPeriodoAgendado.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtPeriodoAgendado.setEnabled(false);
        txtPeriodoAgendado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeriodoAgendadoActionPerformed(evt);
            }
        });
        panelAgendado.add(txtPeriodoAgendado, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 133, 293, 27));

        txtRefeicaoAgendada.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtRefeicaoAgendada.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtRefeicaoAgendada.setEnabled(false);
        panelAgendado.add(txtRefeicaoAgendada, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 67, 293, 27));

        txtValorAgendamento.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtValorAgendamento.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtValorAgendamento.setEnabled(false);
        panelAgendado.add(txtValorAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 100, 293, 27));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setText("Valor:");
        panelAgendado.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 84, 27));

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel6.setText("Período:");
        panelAgendado.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 133, 84, 27));
        jLabel6.getAccessibleContext().setAccessibleName("Período:");

        lbldescTipoAgendamento.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lbldescTipoAgendamento.setText("Agendamento:");
        panelAgendado.add(lbldescTipoAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 67, -1, 27));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setText("CPF:");
        panelAgendado.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 33, 84, 27));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");
        panelAgendado.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 84, 27));

        txtNome.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtNome.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtNome.setEnabled(false);
        panelAgendado.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 0, 293, 28));

        txtSaldo.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtSaldo.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtSaldo.setEnabled(false);
        txtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoActionPerformed(evt);
            }
        });
        panelAgendado.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 34, 128, 27));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel2.setText("Saldo:");
        panelAgendado.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 34, -1, 27));

        txtCpf.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtCpf.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtCpf.setEnabled(false);
        panelAgendado.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 34, 99, 27));

        panelBtnAgendamento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreditoCreditar.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnCreditoCreditar.setText("Creditar");
        btnCreditoCreditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditoCreditarActionPerformed(evt);
            }
        });
        panelBtnAgendamento.add(btnCreditoCreditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 137, -1));

        btnCreditorCancelar.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnCreditorCancelar.setText("Cancelar");
        btnCreditorCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditorCancelarActionPerformed(evt);
            }
        });
        panelBtnAgendamento.add(btnCreditorCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 136, -1));

        panelAgendado.add(panelBtnAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 166, 389, -1));

        getContentPane().add(panelAgendado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 400, 210));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 390, 10));

        scrollpMessages.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpMessages.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        scrollpMessages.setMinimumSize(new java.awt.Dimension(50, 50));

        panelMessages.setAlignmentY(0.0F);
        panelMessages.setLayout(new javax.swing.BoxLayout(panelMessages, javax.swing.BoxLayout.PAGE_AXIS));
        scrollpMessages.setViewportView(panelMessages);

        getContentPane().add(scrollpMessages, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 390, 230));

        pnlRodape.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogado.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        labelLogado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogado.setText("Usuário não esta online.");
        labelLogado.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(255, 255, 255))));
        pnlRodape.add(labelLogado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 36));

        labelSincronizado.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        labelSincronizado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSincronizado.setText("-");
        labelSincronizado.setToolTipText("");
        labelSincronizado.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(255, 255, 255))));
        labelSincronizado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlRodape.add(labelSincronizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 260, 36));

        labelWebService.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        labelWebService.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWebService.setText("Off-Line");
        labelWebService.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(255, 255, 255))));
        labelWebService.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlRodape.add(labelWebService, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 160, 36));

        getContentPane().add(pnlRodape, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 830, 36));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Mensagens:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));
        getContentPane().add(labelImgAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 170, 150));

        menuOpcoes.setText("Opções");
        menuOpcoes.setToolTipText("");
        menuOpcoes.setActionCommand("");
        menuOpcoes.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        menuLogout.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        menuOpcoes.add(menuLogout);

        menuSincronizar.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        menuSincronizar.setText("Sincronizar");
        menuSincronizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSincronizarActionPerformed(evt);
            }
        });
        menuOpcoes.add(menuSincronizar);

        jMenuBar1.add(menuOpcoes);

        menuLogEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogEventMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuLogEvent);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUserNameActionPerformed

    private void menuSincronizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSincronizarActionPerformed
        
    	new Thread(SincronizadorControl.getInstance()).start();
    }//GEN-LAST:event_menuSincronizarActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
		KeycloakSession.getCatracaInstance().logof();
		Splat.getinstance().deslogar();
//    	LoginListenerThread.interruptLogin();
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.callBack(this.textUserName.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtPeriodoAgendadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeriodoAgendadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeriodoAgendadoActionPerformed

    private void txtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoActionPerformed

    private void actionCloseWindow(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_actionCloseWindow
        Log.close();
    }//GEN-LAST:event_actionCloseWindow

    private void menuLogEventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogEventMouseClicked
        System.out.println("clic");
        menuLogout.setSelected(false);
    }//GEN-LAST:event_menuLogEventMouseClicked

    private void btnCreditoCreditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditoCreditarActionPerformed
        PrincipalControl.getPrincipalControl().creditar();
    }//GEN-LAST:event_btnCreditoCreditarActionPerformed

    private void btnCreditorCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditorCancelarActionPerformed
    	PrincipalControl.getPrincipalControl().clearUserInfo();
    }//GEN-LAST:event_btnCreditorCancelarActionPerformed

    private void textUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textUserNameKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.btnBuscarActionPerformed(null);
        }
    }//GEN-LAST:event_textUserNameKeyPressed

    private void txtTipoRefeicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoRefeicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoRefeicaoActionPerformed

    public void callBack(String chave) {
    	PrincipalControl.getPrincipalControl().clearUserInfo();
    	
    	String[] separate = chave.split(":");
    	
//    	if(this.keyOld.equals(chave)||(chave.contains(":") && this.keyOld.equals(separate[0]))) {
//    		System.out.println("Chave ja passada;");
//    		return ;
//    	}else {
//    		
//    		this.keyOld = chave;
//    	}
    	
        if (chave.contains(":")) {
            this.textUserName.setText(separate[0]);
            PrincipalControl.getPrincipalControl().searchUser(separate[1], false);
        } else {
        	this.textUserName.setText(chave);
            PrincipalControl.getPrincipalControl().searchUser(chave, true);
        }

    }

    public void clearUserInfo() {
        this.txtNome.setText("");

        this.txtCpf.setText("");
        this.txtSaldo.setText("");
        this.textUserName.setText("");

        this.txtValorAgendamento.setText("");
        this.txtRefeicaoAgendada.setText("");
        this.txtPeriodoAgendado.setText("");
        this.labelImage.setIcon(null);

        this.setVisibleBtnAcessos(false);
        this.clearMessage();
    }

    public void showUserInfo(APISaldo saldo,APIAgendamento agendamento) {
        this.txtNome.setText(saldo.getUsuario().getNome());

        this.txtCpf.setText(saldo.getUsuario().getCpf());    
        this.txtSaldo.setText(saldo.getSaldo().toString());
    
        if (agendamento != null) {
            this.txtValorAgendamento.setText(agendamento.getRefeicao().getValor().toString());
            this.txtRefeicaoAgendada.setText(agendamento.getRefeicao().getTipoRefeicao().getDescricao());
            this.txtRefeicaoAgendada.setDisabledTextColor(java.awt.Color.decode(agendamento.getRefeicao().getTipoRefeicao().getBackgroundColor()));
            this.txtPeriodoAgendado.setText(agendamento.periodScheduling());
        } else {

        }
        
        APIImagen imagen = this.imagemCDAO.findByUsername(saldo.getUserName());

        BufferedImage image;
        try {
			image = ImageIO.read(new File(Path.of(imagen.getFullPath()).toAbsolutePath().toString()));
            ImageIcon ii = new ImageIcon(image.getScaledInstance(330, 250, Image.SCALE_FAST));
            this.labelImage.setIcon(ii);
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
    
    public void mostraIcone(String path){
        BufferedImage image;
        try {
			image = ImageIO.read(new File(path));
            ImageIcon ii = new ImageIcon(image.getScaledInstance(150, 150, Image.SCALE_FAST));
            this.labelImgAcesso.setIcon(ii);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void addLabelMessage(String msg, Color background, Color forengroud) {
        JLabel label = new JLabel("<html> " + msg + "</html>");
        label.setOpaque(true);
        label.setForeground(forengroud);
        label.setBackground(background);
        label.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238, 105)));
        label.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        label.setAlignmentY(Component.LEFT_ALIGNMENT);

        Font f = label.getFont();

        int stringWidth = label.getFontMetrics(f).stringWidth(label.getText());

        int height = 25 * ((stringWidth / 380) + 1);

//        System.out.println(height);
        label.setMinimumSize(new Dimension(380, height));
        label.setPreferredSize(new Dimension(380, height));
        label.setMaximumSize(new Dimension(380, height));

        this.panelMessages.add(label, 0);

        this.panelMessages.revalidate();
        this.panelMessages.repaint();
    }

    public void showMessageError(String msg) {
        addLabelMessage(msg, new Color(255, 155, 155), Color.black);
    }

    public void showMessageWarning(String msg) {
        addLabelMessage(msg, new Color(255, 249, 192), Color.black); //amarelinho
    }

    public void showMessage(String msg) {
        addLabelMessage(msg, new Color(170, 183, 255), Color.BLACK);
    }
    
    public void showMessageSucess(String msg) {
        addLabelMessage(msg, new Color(89, 182, 164), new Color(255,255,255));
    }
    
    public void catracaOnline(String username) {
    	this.labelWebService.setText("ON-Line");
		this.labelWebService.setForeground(new Color(50, 150, 50));
    	this.labelLogado.setText(username);
    }

	public void catracaOffline(String username) {
    	this.labelWebService.setText("OFF-Line");
		this.labelWebService.setForeground(new Color(200, 50, 50));
		this.labelLogado.setText(username);
    }

    public void clearMessage() {
        this.panelMessages.removeAll();
        this.panelMessages.revalidate();
        this.panelMessages.repaint();
        this.showMessage("Bem vindo!");
        this.labelImgAcesso.setIcon(null);
    }

    public String getOfBack() {
        return this.textUserName.getText();
    }

    public void setLblOnline(String text) {
        //this.lblOnline.setText(text);
    }

//    public TipoRefeicao getTipoRefeicao() {
//        return (TipoRefeicao) cmbTipoRefeicao.getSelectedItem();
//    }

    public void setUserLoged(String user) {
        this.labelLogado.setText(user);
    }
    
    public void setVisibleBtnAcessos(boolean visible){
        this.btnCreditoCreditar.setVisible(visible);
        this.btnCreditorCancelar.setVisible(visible);
    }

	public @Override void toFront() {
		int sta = super.getExtendedState() & ~JFrame.ICONIFIED & JFrame.NORMAL;

		super.setExtendedState(sta);
		super.setAlwaysOnTop(true);
		super.toFront();
		super.requestFocus();
		super.setAlwaysOnTop(false);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCreditoCreditar;
    private javax.swing.JButton btnCreditorCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelImgAcesso;
    private javax.swing.JLabel labelLogado;
    private javax.swing.JLabel labelSincronizado;
    private javax.swing.JLabel labelWebService;
    private javax.swing.JLabel lblRefeicao;
    private javax.swing.JLabel lbldescTipoAgendamento;
    private javax.swing.JMenu menuLogEvent;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenu menuOpcoes;
    private javax.swing.JMenuItem menuSincronizar;
    private javax.swing.JPanel panelAgendado;
    private javax.swing.JPanel panelBtnAgendamento;
    private javax.swing.JPanel panelCam;
    private javax.swing.JPanel panelCatraca;
    private javax.swing.JPanel panelInfoUser;
    private javax.swing.JPanel panelMessages;
    private javax.swing.JPanel pnlRodape;
    private javax.swing.JScrollPane scrollpMessages;
    private javax.swing.JTextField textUserName;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPeriodoAgendado;
    private javax.swing.JTextField txtRefeicaoAgendada;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtTipoRefeicao;
    private javax.swing.JTextField txtValorAgendamento;
    // End of variables declaration//GEN-END:variables

}
