/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.iffar.catra.forms;

import javax.swing.DefaultComboBoxModel;
import javax.ws.rs.NotAuthorizedException;

import br.edu.iffar.catra.control.LoginControl;
import br.edu.iffar.catra.dao.APITipoRefeicaoDAO;
import br.edu.iffar.catra.dao.UsuarioOffLineDAO;
import br.edu.iffar.fw.classBag.db.model.TipoRefeicao;

/**
 *
 * @author darlan
 */
public class Splat extends javax.swing.JFrame implements Runnable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
        
    private APITipoRefeicaoDAO tipoRefeicaoDAO = new APITipoRefeicaoDAO();
	private UsuarioOffLineDAO usuarioOffLineDAO = new UsuarioOffLineDAO();

	private static Splat splat;

	public static Splat getinstance() {
		if(splat == null) {
			splat = new Splat();
		}
		return splat;
	}
	/** 
     * Creates new form Splat
     */
    public Splat() {
        initComponents();
		this.txtUsuario.setText("02365495028");
		this.txtSenha.setText("02365495028");
    }

    
    public void buscaRefeicoes(){
		try {
			cmbTipoRefeicao.setModel(new DefaultComboBoxModel<>(this.tipoRefeicaoDAO.listAllArray()));
		} catch (Exception e) {
			e.printStackTrace();
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        labelSenha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelCarregando = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        lblRefeicao = new javax.swing.JLabel();
        cmbTipoRefeicao = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnLoginOnline = new javax.swing.JButton();
        btnLoginOffline = new javax.swing.JButton();
        labelErroLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 148, 30));

        txtSenha.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 148, 30));

        labelSenha.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        labelSenha.setText("Senha");
        jPanel1.add(labelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel1.setText("Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCarregando.setText("Catraca, carrengando ...");
        jPanel2.add(labelCarregando, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 334, -1));

        progressBar.setValue(10);
        jPanel2.add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 310, -1));

        lblRefeicao.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        lblRefeicao.setText("informe a refeição que esta sendo servida:");
        jPanel2.add(lblRefeicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 20));

        cmbTipoRefeicao.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        cmbTipoRefeicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoRefeicaoActionPerformed(evt);
            }
        });
        jPanel2.add(cmbTipoRefeicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 314, 27));

        btnLoginOnline.setText("Login Online");
        this.btnLoginOnline.setVisible(false);
        btnLoginOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginOnlineActionPerformed(evt);
            }
        });

        btnLoginOffline.setText("Login OffLine");
        this.btnLoginOffline.setVisible(false);
        btnLoginOffline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginOfflineActionPerformed(evt);
            }
        });

        labelErroLogin.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        labelErroLogin.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnLoginOffline, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLoginOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelErroLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addGap(11, 11, 11))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoginOffline)
                    .addComponent(btnLoginOnline))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelErroLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginOnlineActionPerformed

		try {

			if(this.txtUsuario.getText().isEmpty() || this.txtSenha.getText().isEmpty()) {
				return;
			}

			LoginControl lc = new LoginControl();
			lc.loginOnLine(this.txtUsuario.getText(), String.valueOf(this.txtSenha.getPassword()));
			okLogou();

		} catch (NotAuthorizedException e) {
			e.printStackTrace();
			this.labelErroLogin.setText(e.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}
    }//GEN-LAST:event_btnLoginOnlineActionPerformed

    private void btnLoginOfflineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginOfflineActionPerformed
		try {

			if(this.txtUsuario.getText().isEmpty() || this.txtSenha.getText().isEmpty()) {
				return;
			}

			LoginControl lc = new LoginControl();
			lc.loginOffLine(this.txtUsuario.getText(), String.valueOf(this.txtSenha.getPassword()));
			okLogou();
		} catch (NotAuthorizedException e) {
			e.printStackTrace();
			this.labelErroLogin.setText(e.getMessage());
		} catch (Exception e) {
			e.printStackTrace();
		}
    }//GEN-LAST:event_btnLoginOfflineActionPerformed

    private void cmbTipoRefeicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoRefeicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoRefeicaoActionPerformed

	public void okLogou() {
		FormCatra.getInstance().setTipoRefeicao((TipoRefeicao) cmbTipoRefeicao.getSelectedItem());
		setVisible(false);
		FormCatra.getInstance().setVisible(true);
		this.txtSenha.setText("");
	}

	public void deslogar() {
		setVisible(true);
		FormCatra.getInstance().setVisible(false);
		this.txtSenha.setText("");
	}

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Splat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Splat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Splat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Splat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        
//    }
    
    public void run() {
        setVisible(true);
    }
    
    public void setProgress(int value) {
        this.labelCarregando.setText("Catraca, carrengando "+value+"%");
    	this.progressBar.setValue(value);
    }

	public int getProgress() {
		return this.progressBar.getValue();
	}

	public void btnVisible() {
		this.btnLoginOffline.setVisible(true);
		this.btnLoginOnline.setVisible(true);
	}

	public void showErroLogin(String msg) {
		this.labelErroLogin.setText(msg);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginOffline;
    private javax.swing.JButton btnLoginOnline;
    private javax.swing.JComboBox<br.edu.iffar.fw.classBag.db.model.TipoRefeicao> cmbTipoRefeicao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelCarregando;
    private javax.swing.JLabel labelErroLogin;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel lblRefeicao;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
